version: "3"

services:
  asd1:
    image: dockercloud/hello-world
    container_name: asd1
    ports:
      - "5000:80"

  asd2:
    image: dockercloud/hello-world
    container_name: asd2
    ports:
      - "5001:80"

  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - "80:80"

